-- ===========================================================================
-- config.lua
-- Central configuration for the OpenResty AI gateway.
--
-- All values come from /etc/nginx/gateway_env.lua, a Lua table generated by
-- docker-entrypoint.sh from the OS environment (with safe defaults). We read a
-- generated file instead of os.getenv() because in this OpenResty build
-- LuaJIT's os.getenv() returns nil for every variable.
-- ===========================================================================

local _M = {}

local ENV_FILE = "/etc/nginx/gateway_env.lua"

-- Load the env table written by the entrypoint. Never fatal: falls back to {}.
local function load_env()
    local f, err = loadfile(ENV_FILE)
    if not f then
        if ngx then
            ngx.log(ngx.WARN, "config: cannot load ", ENV_FILE, ": ", err)
        end
        return {}
    end
    local ok, data = pcall(f)
    if not ok or type(data) ~= "table" then
        return {}
    end
    return data
end

local E = load_env()

-- Return the configured value or a default.
local function opt(name, default)
    local v = E[name]
    if v == nil or v == "" then
        return default
    end
    return v
end

-- Name of the lua_shared_dict used for the token bucket and retry counters.
-- Must match the `lua_shared_dict <name> <size>` directive in nginx.conf.
_M.shared_dict_name = "gateway"

-- Upstream new-api address (host:port), also used in nginx.conf proxy_pass.
_M.upstream = opt("upstream", "new-api:3000")

-- Global Requests-Per-Minute limit (token-bucket capacity).
_M.rpm_capacity = tonumber(opt("rpm_capacity", 25))

-- Window over which `rpm_capacity` tokens are refilled.
-- refill rate = capacity / window_seconds  (tokens per second).
_M.rpm_window_seconds = tonumber(opt("rpm_window_seconds", 60))

-- Maximum transparent retries when the upstream answers with HTTP 429.
_M.max_429_retries = tonumber(opt("max_429_retries", 5))

-- Base backoff (seconds) applied before each 429 retry.
-- The actual sleep grows linearly: attempt * backoff_seconds.
_M.retry_backoff_seconds = tonumber(opt("retry_backoff_seconds", 1))

-- Hard upper bound (seconds) for a single queued request, so a pathological
-- backlog cannot block a worker forever. Roughly the time to fully refill.
_M.max_queue_wait_seconds = tonumber(opt("max_queue_wait_seconds",
    tostring(_M.rpm_window_seconds)))

return _M
