#!/bin/sh
# Entrypoint for the OpenResty AI gateway.
#
# Renders the nginx config (LISTEN_PORT placeholder -> PORT) and writes a Lua
# config file (/etc/nginx/gateway_env.lua) from the OS environment.
#
# Why a generated file? In this OpenResty build, LuaJIT's os.getenv() returns
# nil for every variable, so config.lua cannot read the environment directly.
# The shell sees the env fine, so we materialise it as a Lua table here.
set -e

PORT="${PORT:-8080}"
UP="${NEW_API_UPSTREAM:-new-api:3000}"
CAP="${RPM_CAPACITY:-25}"
WIN="${RPM_WINDOW_SECONDS:-60}"
RET="${MAX_429_RETRIES:-5}"
BACK="${RETRY_BACKOFF_SECONDS:-1}"
MAXW="${MAX_QUEUE_WAIT_SECONDS:-$WIN}"

# Write the auto-generated Lua config (do not edit by hand).
cat > /etc/nginx/gateway_env.lua <<EOF
-- AUTO-GENERATED by docker-entrypoint.sh. Do not edit.
return {
    upstream             = "$UP",
    rpm_capacity         = $CAP,
    rpm_window_seconds   = $WIN,
    max_429_retries      = $RET,
    retry_backoff_seconds = $BACK,
    max_queue_wait_seconds = $MAXW,
}
EOF

echo "openresty-ai-gateway: listening on :${PORT} (upstream=${UP})"
sed "s/LISTEN_PORT/${PORT}/g" /etc/nginx/nginx.conf > /tmp/nginx.gateway.conf

exec openresty -c /tmp/nginx.gateway.conf -g 'daemon off;'
