#!/bin/sh
# Entrypoint for the OpenResty AI gateway.
#
# Renders the nginx config (LISTEN_PORT placeholder -> PORT) and writes a Lua
# config file (/etc/nginx/gateway_env.lua) from the OS environment.
#
# Why a generated file? In this OpenResty build, LuaJIT's os.getenv() returns
# nil for every variable, so config.lua cannot read the environment directly.
# The shell sees the env fine, so we materialise it as a Lua table here.
set -e

PORT="${PORT:-8080}"
UP="${NEW_API_UPSTREAM:-new-api:3000}"
CAP="${RPM_CAPACITY:-25}"
WIN="${RPM_WINDOW_SECONDS:-60}"
RET="${MAX_429_RETRIES:-5}"
BACK="${RETRY_BACKOFF_SECONDS:-1}"
MAXW="${MAX_QUEUE_WAIT_SECONDS:-$WIN}"
CONC="${MAX_CONCURRENCY:-5}"
CONCPOLL="${CONCURRENCY_POLL_SECONDS:-0.05}"
CONCTIMEOUT="${CONCURRENCY_QUEUE_TIMEOUT_SECONDS:-3600}"
SLOTTTL="${CONCURRENCY_SLOT_TTL_SECONDS:-7200}"
COOLDOWN="${HTTP_ERROR_COOLDOWN_SECONDS:-5}"
MAXCOOLDOWN="${HTTP_ERROR_MAX_COOLDOWN_SECONDS:-60}"
HTTPRET="${MAX_HTTP_ERROR_RETRIES:-1}"

# Write the auto-generated Lua config (do not edit by hand).
cat > /etc/nginx/gateway_env.lua <<EOF
-- AUTO-GENERATED by docker-entrypoint.sh. Do not edit.
return {
    upstream             = "$UP",
    rpm_capacity         = $CAP,
    rpm_window_seconds   = $WIN,
    max_concurrency      = $CONC,
    concurrency_poll_seconds = $CONCPOLL,
    concurrency_queue_timeout_seconds = $CONCTIMEOUT,
    concurrency_slot_ttl_seconds = $SLOTTTL,
    max_429_retries      = $RET,
    max_http_error_retries = $HTTPRET,
    retry_backoff_seconds = $BACK,
    http_error_cooldown_seconds = $COOLDOWN,
    http_error_max_cooldown_seconds = $MAXCOOLDOWN,
    max_queue_wait_seconds = $MAXW,
}
EOF

echo "openresty-ai-gateway: listening on :${PORT} (upstream=${UP})"
sed "s/LISTEN_PORT/${PORT}/g" /etc/nginx/nginx.conf > /tmp/nginx.gateway.conf

exec openresty -c /tmp/nginx.gateway.conf -g 'daemon off;'
